#!/bin/bash

pip install BeautifulSoup
pip install ClientForm
pip install PyRRD
pip install SQLAlchemy
pip install argparse
pip install boto
pip install boto3
pip install botocore
pip install distribute
pip install docutils
pip install fernet
pip install futures
pip install glacier
pip install iotop
pip install iso8601
pip install jmespath
pip install mechanize
pip install mod-python
pip install ordereddict
pip install ping
pip install prettytable
pip install py-rrdtool
pip install pyaes
pip install pyping
pip install python-apt
pip install python-dateutil
pip install python-eeml
pip install pytz
pip install reportbug
pip install s3transfer
pip install simplejson
pip install six
pip install wsgiref
pip install youtube-dl
